#!/bin/bash
#
#SBATCH --job-name=exp214-PhysDime
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=36:00:00
#SBATCH --mem=30GB

module purge
module load gcc/6.3.0
module load cuda/10.1.105

source $(conda info --base)/etc/profile.d/conda.sh
conda activate torch-geometric

export PYTHONPATH=../dataProviders:$PYTHONPATH
python train.py --config_name config-exp214.txt > LOG_exp214.log 2>&1
