#!/bin/bash
#
#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=5:00:00
#SBATCH --mem=30GB

module purge

singularity exec --nv \
            --overlay ~/conda_envs/dnn-3.7-pytorch1.7.0-cuda11.0.ext3:ro \
            /scratch/work/public/singularity/cuda11.0-cudnn8-devel-ubuntu18.04.sif \
            bash -c "source /ext3/env.sh; export PYTHONPATH=../dataProviders:$PYTHONPATH; python test.py --folder_names 'exp*_run_*' --x_forward 0 --n_forward 5 "
