#!/bin/bash
#
#SBATCH --job-name=exp174-PhysDime
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=7GB

module purge
module load gcc/6.3.0
module load cuda/10.1.105

source $(conda info --base)/etc/profile.d/conda.sh
conda activate torch-geometric

export PYTHONPATH=../dataProviders:$PYTHONPATH
python train.py --config_name config-exp174.txt > LOG_exp174.log 2>&1
